{% set name = "globus-identity-mapping" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/globus_identity_mapping-{{ version }}.tar.gz
  sha256: acd8c2efdb7f7c2d3a4e26dcce1a053e9081da903b1815a12164c3433aa66ddb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - click >=8.1.7,<9.0.0
    - python >={{ python_min }}
    - marshmallow <3.22
    - marshmallow-oneofschema >=3.0.1,<4.0.0,!=3.1.0
    - typing-extensions >=4.11
  run_constrained:
    - pytest >=7.4.1,<7.5
    - pytest-cov >=4.1,<4.2
    - pytest-mock >=3.12,<3.13

test:
  imports:
    - globus_identity_mapping
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.globus.org
  summary: 'Globus Identity Mapper Python library'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
