{% set name = "globus-identity-mapping" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globus_identity_mapping-{{ version }}.tar.gz
  sha256: 9d8e73ed4b6edfd20d39eca9365fbeaf913239b01d41ff67fd3b0d645a223fc5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - marshmallow >=3.20.1,<4.0.0
    - marshmallow-oneofschema >=3.0.1,<4.0.0
    - typing-extensions >=4.8,<4.9
  run_constrained:
    - pytest >=7.4.1,<7.5
    - pytest-cov >=4.1,<4.2
    - pytest-mock >=3.12,<3.13

test:
  imports:
    - globus_identity_mapping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.globus.org
  summary: 'Globus Identity Mapper Python library'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
